### ISSUE TITLE
Permissions settings are not working

### ISSUE THREAD

**Issue by Stvad** [toggl/toggl-button#736] opened 2017-01-03 22:54 UTC
### Environment details

* Operation system: Manjaro (Arch) Linux
* Extension version: 1.0.18

### Expected behavior
In options on the permissions tab the list of predefined web-resources provided, where you can select which ones you want to enable.

### Actual behavior
No list displayed. And as it's disabled by default everywhere - I can't really use the extension

### Steps to reproduce the behavior
Go to options, permissions tab

### Additional details
Enable all has no effect on the behaviour.

![image](https://cloud.githubusercontent.com/assets/81347/21626142/6fad8d2a-d207-11e6-95d0-84f404d4078a.png)

**Comment by syko** [comment] 2017-01-04 11:19
Duplicate of #717. Should be fixed in the latest release (1.1.0).

**Closed by syko** 2017-01-04 11:19 UTC
