### ISSUE TITLE
Time tracked on trello no longer updates the "Time tracked"

### ISSUE THREAD

**Issue by float-mode** [toggl/toggl-button#460] opened 2016-02-12 08:53 UTC
I tried this several times in the past couple of days, but the time inside trello cards no longer updates. It remains 0:00:00 no matter how many times I start it and stop it and on several cards I've tried.

I have been logged in to toggl plugin on Chrome, and to the website (so it's not that). I'm not sure what it could be..

**Comment by IndrekV** [comment] 2016-02-12 11:19
Thank you for reporting, we've managed to reproduce this issue and will be working on a fix.

**Comment by topdown** [comment] 2016-02-17 20:31
I'm guessing this is related to the issue I was having all day trying to figure out an error for my buttons
``` Error in event handler for (unknown): TypeError: Cannot read property 'toLowerCase' of undefined ```

It seems to only happen when you render for a list and use `calculateTrackedTime`.
This seems to be the culprit https://github.com/toggl/toggl-button/blob/master/src/scripts/common.js#L145

Changing to this

``` 
calculateTrackedTime: function (desc) {
    var duration = 0,
      description = desc.toLowerCase(),
      projectId = togglbutton.findProjectIdByName(togglbutton.currentProject); 
```

Fixed it for me, so I am guessing digging deeper into `mainDescription` with loops would show an issue.

**Comment by tcrammond** [comment] 2019-05-14 10:56
Closing this one as the feature no longer exists. #508

**Closed by tcrammond** 2019-05-14 10:56 UTC
