### ISSUE TITLE
Unable to log in on Firefox

### ISSUE THREAD

**Issue by lgp171188** [toggl/toggl-button#1458] opened 2019-07-22 14:35 UTC
* **OS version**:  Arch Linux
* **Browser version**:  68.0.1 64-bit
* **Extension version**: 1.39.1

### 🐛 Describe the bug

I installed the Toggl extension on Firefox and clicked the Login button on the extension popup. It redirected to the login page on the Toggle site and after logging in with the credentials, I get redirected to the extension page (moz-extension://7db3be0d-d75f-4ea8-b762-9372d8fe6532/html/login.html?source=web-login) which says `Uh-oh.
Something went wrong... Fetch user failed 403`.

### Expected behaviour

The login flow works correctly and the extension is able to access my account and allow tracking time.

### Steps to reproduce

See the details in the description.

### Other details or context

Since I found similar issues already reported and closed and they were due to cookie issues, I have tried fully disabling all types of cookie blocking (third-party, trackers etc.) but I still see the same behaviour.

**Comment by dooart** [comment] 2019-08-15 21:59
couldn't reproduce in firefox for mac 😞 

will need someone on arch linux to investigate this

**Comment by lgp171188** [comment] 2019-08-28 09:53
@dooart, sorry for the late response. Though this issue was happening repeatedly, the extension was able to log in automatically after a browser restart.

If required, I can try logging out and logging back in to see if this happens even now.

**Comment by dooart** [comment] 2019-08-29 01:47
thanks for letting us know, @lgp171188!

if you're not facing problems anymore, i'll just close the issue for now. please reopen if it happens again.

**Closed by dooart** 2019-08-29 01:47 UTC
Labels: bug, impact: high
