### ISSUE TITLE
Chrome Button seems to be conflicting with Feedly

### ISSUE THREAD

**Issue by Michelle112** [toggl/toggl-button#818] opened 2017-05-09 22:40 UTC
User reached out on Twitter on March 8th stating that the Chrome button was interfering with Feedly.

![feedly](https://cloud.githubusercontent.com/assets/19910107/25875488/63364ecc-34dd-11e7-890c-46142983475e.jpg)

**Comment by syko** [comment] 2017-05-10 05:35
Duplicate of #790

**Closed by syko** 2017-05-10 05:35 UTC
