### ISSUE TITLE
Idle detection settings not saved

### ISSUE THREAD

**Issue by aryehbeitz** [toggl/toggl-button#382] opened 2015-11-22 13:15 UTC
Problem: Idle settings are lost when closing and reopening browser.
Windows 8, chrome
to replicate: click on the toggle icon, settings, uncheck the idle detection.
now close browser and reopen. open settings as before. the idle checkbox is checked again.

in general, idle is good for people who don't get paid when they are idle. in some places, however, there is only a checkin and checkout time. in such cases, idle can be a bother
thanks so much

**Comment by IndrekV** [comment] 2015-11-22 14:44
Duplicate of #380

**Closed by IndrekV** 2015-11-22 14:44 UTC
