### ISSUE TITLE
Popup view not updated after sync / still shows login

### ISSUE THREAD

**Issue by langri-sha** [toggl/toggl-button#805] opened 2017-04-10 21:07 UTC
When signed out, after syncing popup still renders login view.

### Environment details

* Operation system: Arch Linux x64
* Extension version: 1.1.5

### Expected behavior

Popup renders the time entries view.

### Actual behavior

Popup still renders login view.

### Steps to reproduce the behavior

- sign out; browser action renders "x" badge
- go to https://toggl.com/login; browser action renders "x" badge
- sign in; browser action renders "x" badge
- click browser action; browser action now updates to either active or inactive
- popup appears, still renders login view
- close, open again, popup renders the time entries view

### Additional details

![image](https://cloud.githubusercontent.com/assets/77084/24880958/a23e019e-1e3c-11e7-9318-d15c2ee65c7a.png)

**Comment by dooart** [comment] 2019-05-22 18:59
I couldn't reproduce this - could you, @tcrammond?

**Comment by shantanuraj** [comment] 2019-06-18 13:22
Couldn't reproduced likely outdated due to recent login code changes

Closing for now

**Closed by shantanuraj** 2019-06-18 13:22 UTC
Labels: bug
