### ISSUE TITLE
Multiple buttons in Bitbucket

### ISSUE THREAD

**Issue by vdubedout** [toggl/toggl-button#574] opened 2016-06-06 16:49 UTC
Hi,

Create a pull request, navigate between activity <-> commits
-> adds two new buttons each time

<img width="1097" alt="screenshot 2016-06-06 12 44 37" src="https://cloud.githubusercontent.com/assets/657721/15830156/e0e7df3c-2be4-11e6-93ec-7643f2b0d6b1.png">

**Comment by IndrekV** [comment] 2016-06-07 06:05
duplicate of #560
This is already fixed but not yet released.

**Closed by IndrekV** 2016-06-07 06:05 UTC
Labels: integration
