### ISSUE TITLE
Toggl button no longer showing on Teamwork

### ISSUE THREAD

**Issue by ErikOsterud** [toggl/toggl-button#1713] opened 2020-04-16 16:19 UTC
### Environment details

* Operating system: Windows 10, Google Chrome
* Extension version: 1.60.7

### Expected behavior
Toggl button shows next to the task in Task Lists and within Tasks.

### Actual behavior
Toggl button is no longer showing.

### Steps to reproduce the behavior
Open a Task List or Task in Teamwork.

### Additional details
I'm using Teamwork with a Custom Domain and with the domain added to the "Custom URLs for integrations" section in the settings for Toggl. Note: this was working previously and stopped working within the past week or so.

![image](https://user-images.githubusercontent.com/740128/79480516-2ea02000-7fdc-11ea-8855-ad437d946ec7.png)

![image](https://user-images.githubusercontent.com/740128/79480555-3eb7ff80-7fdc-11ea-9caa-ec9a59dfdc7f.png)

**Comment by kornelijepetak** [comment] 2020-07-17 08:36
Closing as a duplicate of #1716

**Closed by kornelijepetak** 2020-07-17 08:36 UTC
