### ISSUE TITLE
Login fail after password change

### ISSUE THREAD

**Issue by AndreyKravchina** [toggl/toggl-button#891] opened 2017-09-21 08:04 UTC
After I had changed password firefox button does not let me log in. I receive error "wrong password or email". In same time I successfuly log in via desktop app and website with same password

**Comment by syko** [comment] 2017-10-02 06:38
Hi,
Is this on chrome or firefox? I see several people having trouble on firefox but I can't reproduce the issue with neither.

**Comment by ohthehugemanatee** [comment] 2017-12-27 11:07
maybe related to #716 ?

**Comment by tcrammond** [comment] 2018-12-07 15:56
If anyone finding their way here experiences a similar problem, please see this comment for a possible resolution: https://github.com/toggl/toggl-button/issues/716#issuecomment-351197454.

Closing this issue as probably related to the above comment.

**Closed by tcrammond** 2018-12-07 15:56 UTC
