### ISSUE TITLE
Login issue with Firefox button

### ISSUE THREAD

**Issue by kadrihvl** [toggl/toggl-button#716] opened 2016-12-02 15:02 UTC
> I recently installed your button add-on on the newly updated firefox running on ubuntu linux. The installation is successful, but I cannot log in through the app.
> When I write in a wrong address/password the app reacts by showing the error message, but when I write in the correct ones it does not react at all.
> I have already done a password reset, but after that I realized that it was not the password the problem (I mentioned that it recognised a wrong email/password combo correctly), but the lack of any reaction.

Case #392313

**Comment by zdericnina** [comment] 2016-12-08 10:38
Another issue with the Log-in button in Firefox:

> I'm trying to use the Firefox add-in with my account and don't seem to be able to log-in. I type in my username and password in the box, but clicking on the green Log In button does nothing.  My account is an email / password combination. The problem is not authentication related, it's a problem with the log in button. When I press the button on the add-in, it does nothing. I can click on the Toggl button and forgot password but, but Log In doesn’t do anything. 

Re-adding the extension didn’t work either or disabling all other add-ins

Case #393837

**Comment by galtish** [comment] 2017-01-28 13:34
I've also hit this error, using Firefox 50.1.0 with the plugin up to date as of the 27th Jan. I've had a go at debugging this:

It looks to me like the loginUser function in src/scripts/backgroud.js doesn't store the API token it receives from the authentication response - it then calls fetchUser with no token, so that that function tries to retrieve a token from local storage, and fails to find one. I've switched the line `TogglButton.fetchUser();` in `loginUser` for `TogglButton.fetchUser(JSON.parse(xhr.responseText).data.api_token);` and can now login and use the plugin as expected.

This can't be the real/whole cause, because then *no-one* would be able to login with the plugin, instead of the apparent few that have been affected. Nevertheless, this fixes this issue for me.

Hope that helps!

**Comment by vedr4n** [comment] 2017-04-25 06:25
Another Firefox/Linux user mentioned the same problem.

Case: 454729

**Comment by CJohnnyB** [comment] 2017-06-14 16:18
Same issue here... with Firefox 53.0.3
This worked before for me... But when I uninstalled the extension and re installed it, the issue started to appear.

**Comment by vedr4n** [comment] 2017-07-06 12:42
Another Linux/Firefox user reporting similar issues. Case: 501199

>>>I am a webdeveloper and tried to debug the addon:
- $loginView is showing
- logic up to the sending of the Ajax request works
- the onError-Callback gets called, but the request data seems empty

Requests:
1. GET /api/v8/me : 403
2. POST /api/v8/sesions: 200 (see screenshot attached)
3. GET /api/v8/me 403

**Comment by vedr4n** [comment] 2017-07-06 12:55
One more Linux/FF user reported the same problem. They are a web developer who tried debugging it themselves. This is what they wrote

>- $loginView is showing
>- logic up to the sending of the Ajax request works
>- the onError-Callback gets called, but the request data seems empty

>Requests:
>1. GET /api/v8/me : 403
>2. POST /api/v8/sesions: 200 (see screenshot attached)
>3. GET /api/v8/me 403

A screenshot of their Network tab is available in case **501199**.

**Comment by dzschille** [comment] 2017-07-25 07:17
I can not login with Ubuntu and FF 54. Issue started today. Why enter credentials i get:
`Error connecting to server`
I use the button every day it just stopped working today. Also remove and reinstall doesn't help.

**Comment by dzschille** [comment] 2017-07-26 07:32
Today the login works again. No restart necessary, just waited a day.

**Comment by EtienneM** [comment] 2017-08-25 14:48
Same problem here on Linux. Tried to remove and install again the addon without much success

**Comment by EtienneM** [comment] 2017-11-21 11:25
Any plan on when you will fix this issue? It would be super convenient for me to use it...

**Comment by vedr4n** [comment] 2017-11-21 11:39
@fonorobert Can you also reproduce this one?

**Comment by fonorobert** [comment] 2017-11-21 15:28
@vedr4n i could successfully log in on FF 57, Manjaro Linux.

@EtienneM what FF version are you running?

**Comment by EtienneM** [comment] 2017-11-21 15:39
I use Firefox 57 on Arch Linux. 
On of my coworker has Firefox 57 on Arch Linux and is successfully using your extension. 

I ran a fresh Firefox with `firefox --profile /tmp`, just installed your extension and it works. Maybe a conflict with an extension I use? 

I disabled all my extensions, deleted Toggl, re-installed Toggl, tried to connect and still nothing... :(
Maybe I should remove all of them but it would be pretty annoying ^^

**Comment by fonorobert** [comment] 2017-11-21 17:13
I'm afraid I'm not sure what could be causing that then. The dev team might have some ideas although it's possible it really is something specific to your setup or one of your other extensions.

**Comment by EtienneM** [comment] 2017-11-22 09:09
Well not only my setup apparently (https://addons.mozilla.org/fr/firefox/addon/toggl-button-time-tracker/reviews/) but I will keep investigating also on my side :-)

**Comment by Gregoyle** [comment] 2017-12-09 03:44
I was able to fix this issue by:

1. Removing the extension 
2. Removing/renaming the Toggl folder under: `.mozilla/firefox/yourid.default/browser-extension-data/toggl-button@toggl.com` 
3. Restart Firefox
4. Re-install the extension.

Hopefully this helps someone else.

**Comment by EtienneM** [comment] 2017-12-11 15:25
Didn't work for me

**Comment by EtienneM** [comment] 2017-12-12 21:17
I got the solution!!!

In a new browser tab, type `about:config`. Ignore the warning and look for the `network.cookie.cookieBehavior` key. Its value is probably something different than `0`. Set it to `0` and the login will work as expected! :D

Here is the documentation about this value: http://kb.mozillazine.org/Network.cookie.cookieBehavior

So this is the value that is changed if you modify the behavior of Firefox about third-party cookies (preferences -> Privacy & Security) and set it to "Never". Setting it to "From visited" or "Always" makes the plugin work :-D

Does it solves the problem for anybody else?

**Comment by ohthehugemanatee** [comment] 2017-12-27 11:00
@EtienneM Wow! Yes, that fix works for me.

If you set the value to 0 ("Always" in the preferences GUI), it should Just Work.
If you want a more restricted value like "from visited" (3 in about:config), add "toggl.com" to the list of cookie exceptions.

**Comment by ohthehugemanatee** [comment] 2017-12-27 11:06
@EtienneM Wow! Yes, that fix works for me.

If you set the value to 0 ("Always" in the preferences GUI), it should Just Work.
If you want a more restricted value like "from visited" (3 in about:config), add "toggl.com" to the list of cookie exceptions.

**Comment by atsux** [comment] 2017-12-27 21:37
@EtienneM Yep, changing setting "Accept third-party cookies" from "never" fixed it for me too. Thank you!

**Comment by dooart** [comment] 2018-01-02 18:11
Considering that the default value of `network.cookie.cookieBehavior` is `0` (which is the one that makes the login work normally), I'm closing this.

Thank you @EtienneM!

**Closed by dooart** 2018-01-02 18:11 UTC
