### ISSUE TITLE
Pomodoro timer is ticked but isn't activating or going "ding"!

### ISSUE THREAD

**Issue by digitaltoast** [toggl/toggl-button#708] opened 2016-11-16 09:44 UTC
Please follow this guide when creating a new issue. This speeds up the process of replicating the issue and finding a solution.

### Environment details

* Operation system: Win 10.1 x64
* Extension version: 1.0.13
* Browser: Chrome Version 55.0.2883.44 beta (64-bit)

### Expected behavior

*DING! After 25 minutes

### Actual behavior

No ding!

### Steps to reproduce the behavior

Tried checking and unchecking Pomodoro options in the button

### Additional info

It used to work, then I stopped using it for a while, now it doesn't work. However, it DOES still correctly start and stop toggl actions. NOTE: I'm using the "new" toggl.

**Comment by IndrekV** [comment] 2016-11-16 12:33
Toggl Button Pomodoro feature works only when timer is started from Toggl Button. This is so by design because otherwise if you leave a computer running and start timer elsewhere, the timer is magically stopped by Toggl Button and user doesn't have any indication why.

**Comment by digitaltoast** [comment] 2016-11-16 16:24
Just to confirm, I am starting the timer from the button. If it's not affecting anyone else, I might try a complete purge and re-install. I thought I'd check if it was just me as it's doing it (or rather, not!) on both my Chrome profiles.

**Comment by IndrekV** [comment] 2016-11-21 04:24
Do you see the pomodoro progress indication in the extension icon?

**Comment by IndrekV** [comment] 2016-11-21 04:26
If all else fails, try to reinstall the extension, this will clear up all the settings and gives you a fresh start.

**Comment by tcrammond** [comment] 2018-12-07 15:52
I'm closing this issue due to age, please re-open if the problem is still present in the latest version from the Chrome store (`1.14.0` +).

**Closed by tcrammond** 2018-12-07 15:52 UTC
Labels: bug
