### ISSUE TITLE
Bitrix24 support

### ISSUE THREAD

**Issue by nicktoggl** [toggl/toggl-button#950] opened 2018-01-03 09:42 UTC
User reporting that Bitrix24 for Toggl Button isn't working for them, even when using custom domains.

"Hello! The Chrome toggle button doesn&#39;t work in bitrix24.com
I&#39;ve connected our bitrix24.ru account - ttn.bitrix24.ru, but the button doesn&#39;t appear.
Please check out your connection with tasks in bitrix24.com.
Thanks!"

case/618132

**Comment by VeljkoTN** [comment] 2018-05-08 14:04
case/690644

**Comment by thirschbuechler** [comment] 2018-10-31 15:29
adding the domain (eg. https://mycompany.bitrix24.de) to the whitelist doesn't help either

**Comment by bryanph** [comment] 2018-11-19 16:41
Duplicate of #899

**Closed by bryanph** 2018-11-19 16:41 UTC
Labels: help wanted
