### ISSUE TITLE
Login issue with Toggl Button

### ISSUE THREAD

**Issue by VeljkoTN** [toggl/toggl-button#1495] opened 2019-09-03 12:28 UTC
* **OS version**: Linux x86_64
* **Browser version**: Firefox 70.0b2
* **Extension version**: don't have that info but considering that they don't have a single time entry created via the Toggl Button before I think we can make a fairly accurate assumption that they just got the extension and are not able to try it because of this issue, so latest version for FF most likely. 

### 🐛 Describe the bug

> I cannot login to the toggl button in the firefox 70.0b2. After pressing a Google login button i see an error as presented in the attached screenshot.

![image](https://user-images.githubusercontent.com/36152180/64173165-f4bc4800-ce56-11e9-9d34-4447f41ee1da.png)

User ID: 1601679
Workspace ID: 860221
Bugsnag link: [🔗 ](https://app.bugsnag.com/toggl-dot-com/toggl-webapp/errors?filters[user.id][0][type]=eq&filters[user.id][0][value]=1601679&filters[app.release_stage][0][value]=production&filters[app.release_stage][0][type]=eq&sort=last_seen)
Case link: [🔗 ](https://app.intercom.io/a/apps/ayixs927/inbox/inbox/2097020/conversations/23504620658)

**Comment by dooart** [comment] 2019-09-10 19:56
related https://github.com/toggl/webapp/issues/11317

**Comment by dooart** [comment] 2019-09-10 20:01
from this intercom conversation and the one in toggl/webapp#11317 it seems it is related to logging in with google

unfortunately i couldn't reproduce the problem, even by installing ublock origin as this user suggested

@VeljkoTN can you please ask the user if they're willing to help us to investigate this by using the network tab and exporting the request data? (i can give you further help with this)

**Comment by dooart** [comment] 2019-09-10 20:04
a little more information on this: the attached screenshot is from toggl button itself, not from the public web: https://github.com/toggl/toggl-button/blob/cb43023e4d2f23c47d315f19eec5e452da90d277/src/scripts/components/LoginPage.tsx#L67

**Comment by VeljkoTN** [comment] 2019-09-11 10:09
I have another user with the same issue: [link ](https://app.intercom.io/a/apps/ayixs927/inbox/inbox/conversation/23603756725)

For the initial case, turning off a blocker called "uBlock Origin" got rid of the 403 error but the user is still not able to log into TB, for this second case removing a blocker called "privacy badger" did not help with the 403 and the login issue is also there. 

@dooart do you mean "export HAR" from the network tab? If it's something else best show me on slack I guess 😄

**Comment by dooart** [comment] 2019-09-11 13:18
@VeljkoTN yeah but they need to tick this checkbox in the network tab before typing the credentials 
![image](https://user-images.githubusercontent.com/371426/64700546-7aef1480-d47d-11e9-9b62-248b1baeb9f4.png)

**Comment by lise-toggl** [comment] 2019-09-12 00:18
[User report](https://app.intercom.io/a/apps/ayixs927/inbox/inbox/unassigned/conversations/23628572884)

**Comment by lise-toggl** [comment] 2019-09-20 05:00
Hi @nunofmn - another user with a HAR file in [this message](https://app.intercom.io/a/apps/ayixs927/inbox/inbox/conversation/23628572884#part_id=comment-23628572884-3778489952).

**Comment by VeljkoTN** [comment] 2019-09-25 08:17
Hey guys, just a friendly followup here - anything new?  :)

**Comment by nunofmn** [comment] 2019-09-25 09:53
We are currently working on improving login. It should fix this problem 👍

**Comment by VeljkoTN** [comment] 2019-09-27 10:31
Another user reached out: [case link 🔗 ](https://app.intercom.io/a/apps/ayixs927/inbox/inbox/unassigned/conversations/23853012495)

**Comment by VeljkoTN** [comment] 2019-10-01 07:10
@nunofmn what's up? :) are close to deploying?

**Comment by tcrammond** [comment] 2019-10-28 16:08
@VeljkoTN We have unfortunately hit various cans of worms. I hope to have some kind of plan for what we're going to do this week.

**Comment by malfter** [comment] 2019-10-31 21:10
I also have a problem logging in to the toggl button:

OS version: Linux x86_64 (Debian)
Browser version: Firefox 68.2.0esr (64-bit)
Extension Version: 1.45.0

![toogl](https://user-images.githubusercontent.com/4189991/67986331-0f2e5a00-fc2b-11e9-963f-70c0c117416c.png)

Restarting the browser does not help.

**Comment by dianetoggl** [comment] 2019-11-03 17:47
[User report](https://app.intercom.io/a/apps/ayixs927/inbox/inbox/unassigned/conversations/24381856701)

**Comment by shantanuraj** [comment] 2019-11-11 07:02
@tcrammond 

Pushed an update to the store today let's wait for some numbers on the [bug tracker](https://app.bugsnag.com/toggl-dot-com/toggl-button/errors/?filters[event.since][0][type]=eq&filters[event.since][0][value]=30d&filters[error.status][0][type]=eq&filters[error.status][0][value]=open&filters[app.context][0][type]=eq&filters[app.context][0][value]=login-page&sort=last_seen)

Should we track login success as well to compare the failure %?

One of the workarounds would be to put an a login-form on the error page as a fallback if the primary mechanism fails.

**Comment by VeljkoTN** [comment] 2019-11-11 12:54
[another user reached out](https://app.intercom.io/a/apps/ayixs927/inbox/inbox/unassigned/conversations/24455568372) about login issues with the FF extension.

**Comment by tcrammond** [comment] 2019-11-12 13:12
Hey @malfter, sorry you're experiencing this problem and thanks for your patience. We're narrowing down the specific scenario in which this occurs. Would you mind checking some of your Firefox settings for me?

First, in `about:preferences#privacy`, does your History setting look like this?

![Screenshot 2019-11-12 at 13 08 21](https://user-images.githubusercontent.com/6432028/68674458-d1480480-054d-11ea-96ea-b72a392c2677.png)

Second, do you have enhanced tracking protection enabled, possibly with one of the stricter cookie options enabled?

![Screenshot 2019-11-12 at 13 09 27](https://user-images.githubusercontent.com/6432028/68674411-bd9c9e00-054d-11ea-8786-69fada149adc.png)

**Comment by malfter** [comment] 2019-11-12 19:25
Hi @tcrammond, here my firefox settings:

to your first point, my history will be saved: "Firefox will Remember History"
![ff-history](https://user-images.githubusercontent.com/4189991/68702833-c14e1600-0589-11ea-9774-c3e78d886250.png)

to your second point, third party cookies are blocked.
![ff-cookies](https://user-images.githubusercontent.com/4189991/68702837-c4490680-0589-11ea-9298-9e3b8af5c7e1.png)

I have disabled all blockers for the toggl login site, but the problem still exists.
![ff-custom-config](https://user-images.githubusercontent.com/4189991/68703148-4cc7a700-058a-11ea-93ff-3fca4afa2e08.png)

**Comment by dianetoggl** [comment] 2019-12-01 18:46
[User report](https://app.intercom.io/a/apps/ayixs927/inbox/inbox/unassigned/conversations/24791086560)

**Comment by dianetoggl** [comment] 2019-12-02 18:29
[User report](https://app.intercom.io/a/apps/ayixs927/inbox/inbox/3540765/conversations/24831432024)

**Comment by nicktoggl** [comment] 2019-12-09 04:52
[User report](https://app.intercom.io/a/apps/ayixs927/inbox/inbox/2097915/conversations/24918846396)

**Comment by nidarasheed** [comment] 2019-12-11 07:54
[Case reference](https://app.intercom.io/a/apps/ayixs927/inbox/inbox/534741/conversations/24955722833)

**Comment by dianetoggl** [comment] 2019-12-11 16:46
[User report](https://app.intercom.io/a/apps/ayixs927/inbox/inbox/3540765/conversations/24950350803)

**Comment by nidarasheed** [comment] 2019-12-13 05:31
[Case reference](https://app.intercom.io/a/apps/ayixs927/inbox/inbox/534741/conversations/24953898726)

**Comment by nidarasheed** [comment] 2019-12-13 11:43
[Case reference](https://app.intercom.io/a/apps/ayixs927/inbox/inbox/534741/conversations/24991909318)

**Comment by dianetoggl** [comment] 2019-12-18 20:52
[Case reference](https://app.intercom.io/a/apps/ayixs927/inbox/inbox/unassigned/conversations/24999261540)

**Comment by shantanuraj** [comment] 2019-12-19 08:37
Latest [release](https://github.com/toggl/toggl-button/releases/tag/1.53.0) (fix landed in #1624)
Contains a fallback-login option that will trigger if the regular web-based-login fails
Users can login using their credentials using that form

![image](https://user-images.githubusercontent.com/1716853/71157694-85812d00-2268-11ea-95d2-243c917e8a73.png)

Closing this for now

**Comment by VeljkoTN** [comment] 2019-12-20 10:18
a user confirmed that they can login now 💪

**Comment by Phenome** [comment] 2020-09-02 10:05
We might have to reopen this. Seems we closed this by having people use the email/password login option, if Google Login failed?

We got a new report on this, and I could repro.

**Comment by Phenome** [comment] 2020-09-02 11:01
It's a new issue; same symptom. Closing.

**Closed by Phenome** 2020-09-02 11:01 UTC
Labels: bug, has pr, impact: high
