### ISSUE TITLE
Can't see/edit/set permissions on extension options

### ISSUE THREAD

**Issue by tupaschoal** [toggl/toggl-button#725] opened 2016-12-20 14:29 UTC
### Environment details
Windows 7
Chrome Version 55.0.2883.87 m
Toggl Button Version (1.0.18)

### Expected behavior
Ability to see default domains and custom domains, as well as selecting them and adding.

### Actual behavior
Nothings is shown, user can't add/edit/view permissions.

### Steps to reproduce the behavior
- Add permissions/custom domains
 to toggl button
- Remove button from Chrome
- Reinstall button
- Try to add custom domain

### Additional details
It's not clear that the steps to reproduce will work, because I couldn't get the permissions to be shown again to test.
![blank](https://cloud.githubusercontent.com/assets/6443427/21354093/ce23afaa-c6af-11e6-8d48-9bf7f8e5b996.PNG)

**Comment by IndrekV** [comment] 2016-12-20 16:49
This issue is fixed just not yet released. Duplicate of #717

**Closed by IndrekV** 2016-12-20 16:49 UTC
