### ISSUE TITLE
Gitlab: Cannot select tag in firefox integration

### ISSUE THREAD

**Issue by bflorat** [toggl/toggl-button#1497] opened 2019-09-04 16:36 UTC
* **OS version**: 
Fedora release 29 (Twenty Nine)

* **Browser version**: 
Firefox 66.0.4 64 bits

* **Extension version**: 
Version 1.40.7

#### Relevant integration (if any):
gitlab.com

### 🐛 Describe the bug
In gitlab.com, I start the timer, then I try to select one or more tags but when I click on the tag, the popup closes and none tag is selected

Note : this bug is NOT in chrome

### Expected behaviour
Same than in chrome : be able to select one or more tags when starting a time

### Other details or context
- Open a integrated website
- Start a time
- Try to select a tag

### Workaround
Use chrome instead of firefox

**Comment by SuperOmario** [comment] 2019-10-02 17:55
Hi I'd like to take this issue? Would you be able to point me in the right direction to start?

**Comment by SuperOmario** [comment] 2019-10-02 19:47
I have tried to replicate the bug but the tags seem to be working in firefox

**Comment by lise-toggl** [comment] 2019-10-09 01:50
@SuperOmario Thanks so much for the interest!

I think this issue will be fixed by https://github.com/toggl/toggl-button/pull/1517 - @nunofmn could you please confirm?

**Comment by bflorat** [comment] 2019-10-09 08:03
@lise-toggl : I don't think so, still the same with 1.42.1, please check out the provided screencast
![vokoscreen-2019-10-09_09-54-59](https://user-images.githubusercontent.com/203516/66462736-060efa80-ea7c-11e9-8275-ce7c5d3969e3.gif)

**Comment by glensc** [comment] 2020-01-20 09:04
@bflorat perhaps you have some conflicting extension installed, have you tried that in a pristine environment (incognito or fresh profile)?

**Comment by tcrammond** [comment] 2020-01-27 12:40
Sorry that there wasn't a quicker conclusion to this thread. It looks like the problem is solved at this point and there haven't been further reports, so I'll close the issue. I could not reproduce the bug under Firefox nor Chrome.

Please let us know if anyone is still experiencing problems and we'll get right on it 🙇

**Closed by tcrammond** 2020-01-27 12:40 UTC
Labels: bug, good first issue, impact: low

**Comment by bflorat** [comment] 2020-01-27 20:19
I confirm it is fixed under Firefox. Thanks.
