### ISSUE TITLE
Visual Studio/Azure Devops issue when selecting projects

### ISSUE THREAD

**Issue by nicktoggl** [toggl/toggl-button#1442] opened 2019-06-20 05:48 UTC
#### Relevant integration (if any):

Visual Studio/Azure Devops

### 🐛 Describe the bug

"After clicking “Start timer” I would love to be able to search Projects, filtering with keyboard, but instead my keys are being ignored by Toggl and captured by Visual Studio instead – so it will change my navigation or other crazy things.

I’m just curious if this is a known issue and is there a plan to fix?"

### Expected behaviour

Keyboard actions should act on Toggl button selection, not on Visual Studio/Azure Devops

[Case](https://app.intercom.io/a/apps/ayixs927/inbox/inbox/2097915/conversations/22483449295)

**Comment by MilesBlueshift** [comment] 2019-11-15 02:10
The issue has become even worse in version 1.46.5. Now, not only can I not search for a project, I cannot select a project at all. Clicking the Project dropdown does nothing.

**Comment by MilesBlueshift** [comment] 2020-01-22 22:50
@nicktoggl the issue has been fixed as of the 1.56.2 release. Thanks!

**Comment by MilesBlueshift** [comment] 2020-01-23 01:19
@nicktoggl never mind that last message Nick. It seemed to work once, but the issue is back again.

**Comment by MilesBlueshift** [comment] 2020-05-28 02:50
@nicktoggl the issue is fixed thanks to @lise-toggl 
PR: https://github.com/toggl/toggl-button/pull/1740

**Closed** 2020-06-03 00:50 UTC
Labels: bug, impact: low
