### ISSUE TITLE
Button is completely grey in Asana integration

### ISSUE THREAD

**Issue by zdericnina** [toggl/toggl-button#1835] opened 2020-09-08 10:00 UTC
* **OS version**: 10.15.6
* **Browser version**: Chrome 85
* **Extension version**: 1.66.1

#### Relevant integration (if any):

Asana (same behavior in Todoist)

### 🐛 Describe the bug

The button is entirely grey until you click on it and it turns purple

<img width="374" alt="Screenshot 2020-09-08 at 11 57 55" src="https://user-images.githubusercontent.com/19727123/92462251-8a0cbd80-f1ca-11ea-9c20-a54bb9e80af9.png">

### Expected behaviour

The button show correctly with our logo

### Other details or context

[Case reference](https://app.intercom.com/a/apps/ayixs927/inbox/inbox/2759100/conversations/106481303544488)

**Comment by TheSoloJake** [comment] 2020-09-08 21:01
[Case reference](https://app.intercom.com/a/apps/ayixs927/inbox/inbox/2137598/conversations/106481303545203)

**Comment by kornelijepetak** [comment] 2020-10-16 13:07
Seems to be a duplicate of https://github.com/toggl/toggl-button/issues/1862

**Closed by kornelijepetak** 2020-10-16 13:07 UTC
Labels: bug
