### ISSUE TITLE
Asana: Newly created tasks are not tracked correctly when hitting Start Timer

### ISSUE THREAD

**Issue by TheSoloJake** [toggl/toggl-button#1646] opened 2020-01-13 16:13 UTC
* **Browser version**: Chrome Latest
* **Extension version**: 1.56.1

#### Relevant integration (if any):

Asana webapp 

### 🐛 Describe the bug

After just creating a new task in the Asana webapp's Task List view, clicking on the TogglButton next to the task will not copy the task name over to the TE description 

### Expected behaviour

No matter how "new" the task is, the Button should copy the task name over. 

### Steps to reproduce

1. Go to Asana webapp 
2. Create new task on task list 
3. Click on TogglButton next to task name 
4. Timer will start w/o description 

### Other details or context

I can't replicate, but this user ([case reference](https://app.intercom.io/a/apps/ayixs927/inbox/inbox/conversation/24705809818)) is experiencing it.

**Comment by lise-toggl** [comment] 2020-01-15 01:47
I could only reproduce this in the My Tasks view, which makes sense because that's the only one where the description selector isn't a function.

I've made a quick fix so that the description is filled in.

Unfortunately the button won't show as active (red) after clicking but this also affects the other views so I'll create another issue for that to be fixed in the future :(

**Closed** 2020-01-15 11:45 UTC
Labels: bug, has pr
