### ISSUE TITLE
Button no longer shows on Gmail / Google mail 

### ISSUE THREAD

**Issue by ricotheque** [toggl/toggl-button#1405] opened 2019-05-14 01:42 UTC
* **OS version**: Windows 10
* **Browser version**: Chrome Version 74.0.3729.131 (Official Build) (64-bit)
* **Extension version**: 1.35.0

#### Relevant integration (if any):

https://mail.google.com

### 🐛 Describe the bug

The timer button no longer appears on Google mail as shown at https://github.com/toggl/toggl-button/wiki/Where-can-I-find-the-Button%3F#google-mail

### Expected behaviour

The timer button should appear on Google mail as shown at https://github.com/toggl/toggl-button/wiki/Where-can-I-find-the-Button%3F#google-mail

### Steps to reproduce

Steps to reproduce the behaviour:
1. Enable mail.google.com under Integrations list
2. Restart browser
3. See no Start timer button when opening a conversation

### Other details or context

The current workaround is to right-click on a space near the subject line then select "Start Timer"

![image](https://user-images.githubusercontent.com/5687885/57664927-901d7900-762c-11e9-8171-3554e0a26b98.png)

**Comment by ricotheque** [comment] 2019-05-14 01:42
[case](https://app.intercom.io/a/apps/ayixs927/inbox/inbox/unassigned/conversations/22009910172)

**Comment by shantanuraj** [comment] 2019-05-14 09:06
@ricotheque I can't really reproduce this on my end, could be a DOM change on gmail's part that's being rolled out in stages.

Still for my sanity can you check if the integration is enabled in the extension settings

and can you execute this in your gmail console and tell me the output

```javascript
document.querySelector('.ha').innerText
```

**Comment by ApocalypticFish** [comment] 2019-07-15 11:52
@shantanuraj Hey mate, the customer got back to us:
this is the result of the selector: document.querySelector('.ha').innerText
"Re: GMail not showing Toggl button
Doručená pošta

x
General

x"

It is the Subject of the e-mail, Inbox in Czech language and label General.

**Comment by shantanuraj** [comment] 2019-07-15 15:05
@ApocalypticFish yeah the statement's result is as expected (the TE description selector for button)
I am not sure what the problem is. Two possible debugging steps

- Check the browser console for any errors from toggl-button
- Ensure the gmail/google mail integration is enabled

**Comment by ApocalypticFish** [comment] 2019-07-17 09:54
![image](https://user-images.githubusercontent.com/18132080/61366294-92e55600-a889-11e9-9995-0dd3b1ccb7ae.png)

**Comment by ApocalypticFish** [comment] 2019-07-17 09:54
Can confirm that the integration is enabled as well.

**Comment by ApocalypticFish** [comment] 2019-07-17 09:54
@shantanuraj

**Comment by lise-toggl** [comment] 2019-11-08 00:29
Original user reported that integration started working again when he started with a new Chrome profile, and support haven't seen any other reports so closing this for now.

**Closed by lise-toggl** 2019-11-08 00:29 UTC
Labels: bug, good first issue, impact: high
