### ISSUE TITLE
Toggl Button reminder interval setting not visible

### ISSUE THREAD

**Issue by VeljkoTN** [toggl/toggl-button#1084] opened 2018-07-18 12:20 UTC
### Environment details

* Operation system: Windows 10 Home
* Extension version: 1.10.9

### Expected behavior
When I access the settings page and turn on reminders by ticking the box next to that option I should also be able to set the reminder interval

### Actual behavior
The interval setting is not visible: 

### Steps to reproduce the behavior
Not sure what exactly is causing this, I tried changing scaling options for my display as well as zooming out and it did not make a difference

* screenshots or screencapture:

![image](https://user-images.githubusercontent.com/36152180/42880727-8ba2f414-8a95-11e8-8ecd-b2a6eebf0032.png)

**Comment by langri-sha** [comment] 2018-08-29 13:32
Duplicate of https://github.com/toggl/toggl-button/issues/1074.

**Closed by langri-sha** 2018-08-29 13:32 UTC
