### ISSUE TITLE
Add ...The most important feature of pomodoro custom rest timer!

### ISSUE THREAD

**Issue by mrRamezanzad** [toggl/toggl-button#1703] opened 2020-04-05 06:42 UTC
Hi! 
Your application is almost perfect BUT how did you decide not to add the rest timer for the pomodoro section and just live it to the user to go rest and come back and every damn time he should either remember to set an alarm or a ticking timer or just come back at proper time,
this need is so obvious that I  wanted to Alert you by issuing a bug.
can't believe that a good product like yours just ignored this simple but one of the most features that every small pomodoro extension in firefox or chrome has it and you just crippled yours by not just adding it, Well thats a shame!
Good luck,

**Comment by jrojer** [comment] 2020-05-26 10:38
this issue is a duplicate of [this one](https://github.com/toggl/toggl-button/issues/597)

**Comment by lise-toggl** [comment] 2020-06-23 08:54
Thanks for the suggestion! We do have plans to add this as part of #1569 so I'm closing this as a duplicate; if you have any further suggestions on the break timer please add it to either #1569 or #597 :)

**Closed by lise-toggl** 2020-06-23 08:54 UTC
Labels: duplicate, enhancement
