### ISSUE TITLE
Google Inbox - Missing "Start Timer" Functionality for Extension and Emails

### ISSUE THREAD

**Issue by mattboroi** [toggl/toggl-button#612] opened 2016-07-21 12:38 UTC
Unable to utilize the Toggl extension (1.0.2) in Chromium (51.0.2704.79) on Ubuntu (16.04 amd64).

![image](https://cloud.githubusercontent.com/assets/1191745/17022720/9975a826-4f1d-11e6-9bf2-8b4aae6282e6.png)

The start timer button is also not available in emails to trigger the timer and begin tracking for the selected subject. 

* Attempted a reinstall through the Chrome store and restarted browser
* Confirmed the domain (inbox.google.com) is enabled

**Comment by IndrekV** [comment] 2016-07-21 13:38
duplicate of #611

This is fixed just not released yet.

**Closed by IndrekV** 2016-07-21 13:38 UTC
