### ISSUE TITLE
When filtering permissions the screen content disappears

### ISSUE THREAD

**Issue by eatskolnikov** [toggl/toggl-button#600] opened 2016-07-13 02:42 UTC
To replicate the issue:
1. Open chrome://extensions tab
2. Look for Toggl
3. Open the options menu
4. Go to the permissions tab
5. Write in the "Filter permissions textbox"

![](http://g.recordit.co/TgokKVPGM0.gif)

**Comment by IndrekV** [comment] 2016-07-13 07:13
I'm currently not able to reproduce this. Does it happen all the time or only when the browser window is at certain size (full screen or windowed)

**Comment by eatskolnikov** [comment] 2016-07-13 12:31
It happens all the time, with either windowed or fullscreen browser.

**Comment by IndrekV** [comment] 2016-07-13 13:18
Still no luck. I tested with latest Chrome on Windows and Mac. Can't reproduce this issue.

**Comment by eatskolnikov** [comment] 2016-07-13 18:49
I'm using a mac mid 2013, 16gb ram and I just updated to the latest chrome version, tried again and it is still happening. I'll look into it and update this if I find something.

**Comment by IndrekV** [comment] 2016-09-19 11:41
We have not received any other feedback about this issue so I'm closing this for now.

**Closed by IndrekV** 2016-09-19 11:41 UTC
Labels: bug

**Comment by desrod** [comment] 2016-11-10 20:21
I can confirm this is consistent on Chrome v56.0.2906.0 dev (64-bit) on Linux using Toggl Button v1.0.13. I can disable, delete, reinstall, and the 'Filter Permissions' is ALWAYS blank. It used to show a list of boilerplate sites (wordpress, salesforce, etc.) and now shows nothing at all. Adding sites by URL manually also results in an empty dataset. Definitely a bug.

**Comment by IndrekV** [comment] 2016-11-11 11:34
@desrod I think your issue might be connected to this one #705

In some cases the list data loading failed.
