### ISSUE TITLE
In Voice Over mode on macOS in chrome when timer is running clock updates are said every second

### ISSUE THREAD

**Issue by madhaze** [toggl/toggl-button#1128] opened 2018-09-13 18:21 UTC
### Environment details

* Operation system: macOS 10.12.6
* Extension version: Version (1.11.1)

### Expected behavior
Toggle Timer extension not a make Voice Over impossible to use in macOS due to continually 
 vocalizing timers seconds update.

### Actual behavior
Timer updates vocalized every second when in Voice Over mode in macOS

### Steps to reproduce the behavior
1. start timer in chrome
2. Enable Voice Over on mac
3. navigate between tabs in chrome 
4. Here voice over continually say "1 2" "2 3" "3 4" "4 5" "5 6" "6 7" and on and on and on.

**Comment by dooart** [comment] 2018-09-13 21:00
Hey, @madhaze, thank you for reporting this. I followed the steps you provided but couldn't reproduce the problem. Could you please give us more information?

**Comment by rylek90** [comment] 2018-09-18 13:18
Hello @madhaze, thanks for finding it out. However, it seems like a Chrome issue, constantly reading updating tab title even if it's not active.

As a current workaround you can disable `Show running time on the title bar` in your profile preferences, you can read more [here](https://support.toggl.com/my-profile/).

Please reach us out in case of any further questions.

**Comment by tcrammond** [comment] 2019-05-14 11:35
I'm closing this issue based on the advice in the above comment, please let us know if there are further related problems.

**Closed by tcrammond** 2019-05-14 11:35 UTC
Labels: awaiting-response
